###########
# site.title

title:    'Avengers'
subtitle: 'CS 175: Project in AI (in Minecraft):Maze Solver'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
